"""Add is_approved status to Organizer

Revision ID: 0a5b7591cd2e
Revises: aed61910c296
Create Date: 2025-09-21 14:33:39.345778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a5b7591cd2e'
down_revision = 'aed61910c296'
branch_labels = None
depends_on = None


# Yeni, düzəldilmiş versiya
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizer', schema=None) as batch_op:
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###
