"""Add graded_at to Answer model

Revision ID: 1fbde8d26845
Revises: 3fd8d5d99254
Create Date: 2025-09-13 23:08:02.644763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fbde8d26845'
down_revision = '3fd8d5d99254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('graded_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_column('graded_at')

    # ### end Alembic commands ###
