"""Add final features to models

Revision ID: 39645b63da80
Revises: 1fbde8d26845
Create Date: 2025-09-14 22:09:23.810000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '39645b63da80'
down_revision = '1fbde8d26845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.String(length=300), nullable=True))

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_start_time', sa.Integer(), nullable=True))

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_spent_per_question', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_column('time_spent_per_question')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('video_start_time')

    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.drop_column('video_url')

    # ### end Alembic commands ###
