"""Add contact to affiliate and new relations

Revision ID: 976b42e97760
Revises: 44b4834086d4
Create Date: 2025-09-19 02:54:43.872880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976b42e97760'
down_revision = '44b4834086d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affiliate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('commission_rate', sa.Float(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_commission', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('registration_commission')

    with op.batch_alter_table('affiliate', schema=None) as batch_op:
        batch_op.drop_column('commission_rate')
        batch_op.drop_column('contact')

    # ### end Alembic commands ###
