"""Add bank_account to Affiliate

Revision ID: aed61910c296
Revises: 976b42e97760
Create Date: 2025-09-19 04:04:04.564430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed61910c296'
down_revision = '976b42e97760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affiliate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_account', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affiliate', schema=None) as batch_op:
        batch_op.drop_column('bank_account')

    # ### end Alembic commands ###
